### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Default4152** [michelleramsundar/bwa-u4-feature-request#4]
Grade : **Needs Improvement**

I like the idea of adding an additional way for users to search faster, in particular the "Enter" key. I think the technical design is thought out but could use some better naming for the methods, as well as the nomenclature of "onSearch property" which should be "onSearch method". The caveats identify a good point about increased errors and more frustration from users if that error occurred. I would recommend trying to think about some more caveats that might come to mind because expanding on the "reducing errors" idea is important. 

Next steps: I would attempt this once more. Try to elaborate more on the caveats!

**Comment by michelleramsundar** [comment]
I've made the suggested changes and am resubmitting shortly. Thank you so very much for your feedback!
